### ISSUE TITLE
@Override in directiveToLine not compiling due to the method not existing in parent

### ISSUE THREAD

**Issue by Javi** [gregopet/stylus-asset-pipeline#3]
I can't make the plugin run with the latest asset-pipeline plugin and Grails 2.4.3, possibly higher, due to compilation exceptions. When manually deleting the annotation, I get "Error loading plugin manager: null" when compiling.

**Comment by gregopet** [comment]
That error is not related to the Grails version, asset pipeline made some changes that broke this plugin. I've got most of it fixed already, hoping to release an updated version today or tomorrow.

**Comment by gregopet** [comment]
I've uploaded ver. 0.8.5 of the plugin which works with newer asset pipeline versions though it didn't get published on the plugins portal (some exception occured). It seems I'll need to upload a 0.8.6 anyway (a small bug showed up once I started using the updated plugin in another project), but most of the functionality should work now. Please add a comment to this issue if it doesn!

And thank you for posting this issue :+1:
